/**
 * Stoop database schema (Drizzle ORM).
 *
 * Conventions:
 * - All tables use `id` (uuid, primary key) generated by Postgres.
 * - All tables include `created_at` and `updated_at` timestamps.
 * - Geographic columns use PostGIS `geography(Point, 4326)` so we can do
 *   distance queries in meters out of the box. PostGIS must be enabled in
 *   Supabase: `create extension if not exists postgis;`
 * - Enums live alongside their primary owning table.
 */

import { sql } from "drizzle-orm";
import {
  pgTable,
  pgEnum,
  uuid,
  text,
  timestamp,
  integer,
  numeric,
  boolean,
  jsonb,
  customType,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";

/* -------------------------------------------------------------------------- */
/*  PostGIS geography type                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Custom Drizzle type for PostGIS `geography(Point, 4326)`.
 * Stored as WKT in JS land; SQL casts handle conversion.
 */
export const geography = customType<{
  data: string;
  driverData: string;
}>({
  dataType() {
    return "geography(Point, 4326)";
  },
});

/* -------------------------------------------------------------------------- */
/*  Enums                                                                     */
/* -------------------------------------------------------------------------- */

export const userRole = pgEnum("user_role", [
  "homeowner",
  "tradesperson",
  "admin",
]);

export const tradeCategory = pgEnum("trade_category", [
  "handyman",
  "plumbing",
  "electrical",
  "painting",
  "appliance_repair",
]);

export const jobStatus = pgEnum("job_status", [
  "open",
  "awarded",
  "in_progress",
  "completed",
  "cancelled",
]);

export const jobUrgency = pgEnum("job_urgency", [
  "flexible",
  "this_week",
  "asap",
]);

export const bidStatus = pgEnum("bid_status", [
  "pending",
  "accepted",
  "rejected",
  "withdrawn",
]);

export const waitlistRole = pgEnum("waitlist_role", [
  "homeowner",
  "tradesperson",
]);

/* -------------------------------------------------------------------------- */
/*  Core user model                                                           */
/* -------------------------------------------------------------------------- */

/**
 * Application-level user row. The id MUST match `auth.users.id` in Supabase,
 * which lets us use Supabase RLS (`auth.uid()`) directly against this table.
 */
export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey(),
    email: text("email").notNull(),
    name: text("name"),
    role: userRole("role").notNull(),
    phone: text("phone"),
    avatarUrl: text("avatar_url"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    emailIdx: uniqueIndex("users_email_idx").on(table.email),
  })
);

/* -------------------------------------------------------------------------- */
/*  Profiles                                                                  */
/* -------------------------------------------------------------------------- */

export const homeownerProfiles = pgTable("homeowner_profiles", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  addressLine: text("address_line"),
  neighborhood: text("neighborhood"),
  /** PostGIS point. Build with `ST_SetSRID(ST_MakePoint(lng, lat), 4326)`. */
  location: geography("location"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const tradespersonProfiles = pgTable("tradesperson_profiles", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  businessName: text("business_name"),
  bio: text("bio"),
  /** Trades offered. Stored as text[] (mirrors the trade_category enum). */
  trades: text("trades").array().notNull().default(sql`'{}'`),
  yearsExperience: integer("years_experience"),
  licenseNumber: text("license_number"),
  insuranceCarrier: text("insurance_carrier"),
  hourlyRateLow: numeric("hourly_rate_low", { precision: 10, scale: 2 }),
  hourlyRateHigh: numeric("hourly_rate_high", { precision: 10, scale: 2 }),
  /** Where they're willing to work from (origin point). */
  homeBase: geography("home_base"),
  /** Service radius in meters. */
  serviceRadiusMeters: integer("service_radius_meters").default(8000),
  verified: boolean("verified").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/* -------------------------------------------------------------------------- */
/*  Jobs + bids                                                               */
/* -------------------------------------------------------------------------- */

export const jobs = pgTable(
  "jobs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    homeownerId: uuid("homeowner_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    trade: tradeCategory("trade").notNull(),
    title: text("title").notNull(),
    description: text("description").notNull(),
    photos: text("photos").array().notNull().default(sql`'{}'`),
    budgetLow: numeric("budget_low", { precision: 10, scale: 2 }),
    budgetHigh: numeric("budget_high", { precision: 10, scale: 2 }),
    urgency: jobUrgency("urgency").notNull().default("flexible"),
    status: jobStatus("status").notNull().default("open"),
    location: geography("location"),
    neighborhood: text("neighborhood"),
    awardedBidId: uuid("awarded_bid_id"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    homeownerIdx: index("jobs_homeowner_idx").on(table.homeownerId),
    statusIdx: index("jobs_status_idx").on(table.status),
    tradeIdx: index("jobs_trade_idx").on(table.trade),
  })
);

export const bids = pgTable(
  "bids",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    jobId: uuid("job_id")
      .notNull()
      .references(() => jobs.id, { onDelete: "cascade" }),
    tradespersonId: uuid("tradesperson_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    price: numeric("price", { precision: 10, scale: 2 }).notNull(),
    message: text("message"),
    etaDays: integer("eta_days"),
    status: bidStatus("status").notNull().default("pending"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    jobIdx: index("bids_job_idx").on(table.jobId),
    tradespersonIdx: index("bids_tradesperson_idx").on(table.tradespersonId),
    /** A tradesperson can only have one active bid per job. */
    uniqueActiveBid: uniqueIndex("bids_unique_active").on(
      table.jobId,
      table.tradespersonId
    ),
  })
);

/* -------------------------------------------------------------------------- */
/*  Reviews. The neighbor-trust feature.                                       */
/* -------------------------------------------------------------------------- */

/**
 * Reviews are written by one user about another (typically homeowner -> tradesperson,
 * occasionally the reverse). We capture the reviewer's location AT THE TIME OF
 * THE REVIEW so we can rank reviews shown to a viewer by physical proximity.
 *
 * Example query (find reviews of tradesperson X near the current viewer):
 *
 *   SELECT r.*, ST_Distance(r.reviewer_location, $viewer_location) AS distance
 *   FROM reviews r
 *   WHERE r.subject_user_id = $X
 *   ORDER BY distance ASC NULLS LAST
 *   LIMIT 10;
 */
export const reviews = pgTable(
  "reviews",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    reviewerId: uuid("reviewer_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    subjectUserId: uuid("subject_user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    jobId: uuid("job_id").references(() => jobs.id, {
      onDelete: "set null",
    }),
    /** 1 to 5 stars. */
    rating: integer("rating").notNull(),
    comment: text("comment"),
    /** Reviewer's geographic position when leaving the review. */
    reviewerLocation: geography("reviewer_location"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    subjectIdx: index("reviews_subject_idx").on(table.subjectUserId),
    reviewerIdx: index("reviews_reviewer_idx").on(table.reviewerId),
  })
);

/* -------------------------------------------------------------------------- */
/*  Waitlist                                                                  */
/* -------------------------------------------------------------------------- */

export const waitlist = pgTable(
  "waitlist",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    email: text("email").notNull(),
    role: waitlistRole("role").notNull(),
    neighborhood: text("neighborhood"),
    tradesInterested: text("trades_interested").array().default(sql`'{}'`),
    referralSource: text("referral_source"),
    metadata: jsonb("metadata"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => ({
    emailRoleIdx: uniqueIndex("waitlist_email_role_idx").on(
      table.email,
      table.role
    ),
  })
);

/* -------------------------------------------------------------------------- */
/*  Convenience types                                                         */
/* -------------------------------------------------------------------------- */

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

export type Job = typeof jobs.$inferSelect;
export type NewJob = typeof jobs.$inferInsert;

export type Bid = typeof bids.$inferSelect;
export type NewBid = typeof bids.$inferInsert;

export type Review = typeof reviews.$inferSelect;
export type NewReview = typeof reviews.$inferInsert;

export type WaitlistEntry = typeof waitlist.$inferSelect;
export type NewWaitlistEntry = typeof waitlist.$inferInsert;
